[build]
  functions = "functions"

[dev]
  functions = "functions"
  autoLaunch = false
  command = "npm run serve"
  targetPort = 8888

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api"
  status = 200
